#----------

# GitHub-basics
#-----
name: My-GitHubActions-Basics


on: 
  push:
    branches:
      -master

jobs:
  my_testing:
    runs-on: ubuntu-latest

steps:
-name: Print Hello world Message
 run:  echo "Hello world from Testing job"
  

my_deploy:
  runs-on: ubuntu-latest

  steps:
  - name: Print hello world
    run: echo "Hello World from deploy job"
