#----------

# GitHub-basics
#-----
name: My-GitHubActions-Basics


on: 
  push:
    branches:
      -master

jobs:
  my_testing:
    runs-on: ubuntu-latest

steps:
-name: Print Hello world Message
 run: echo Hello world from testing job
  
my_deploy:
  runs-on: ubuntu-latest
  steps:
  - name: Print hello world
